# Generated by Django 4.0.4 on 2022-04-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgsales_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='eu_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='global_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='jp_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='na_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
