# Generated by Django 4.0.4 on 2022-04-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgsales_api', '0002_alter_game_eu_sales_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
